model_simulation_node:
  ros__parameters:
    alpha: 0.012                # the unknown input gain
    beta: -0.01               # the unknown damping coefficient
    delta: -0.1                 # a fixed unknown disturbance
    wheelbase: 0.5              # wheelbase (L)
    base_frame: "robot_1"       # name for this robot instance

    frequency: 20.0             # integration rate [Hz]
    s0: 0.0                     # initial s (longitudinal position)
    l0: 0.0                     # initial l (lateral position)
    psi0: 0.0                   # initial psi (yaw/heading angle)
    v0: 0.0                     # initial velocity

    # Dynamic parameters
    # torque: 100.0               # the input torque
    phi: 0.05                   # the input steering angle

longitudinal_controller_node:
  ros__parameters:
    gamma_alpha: 0.001
    gamma_beta: 0.0001
    gamma_delta: 0.01

    k_1: 3.0
    k_2: 0.3

    # v_des: 25.0
    frequency: 20.0

    alpha_bar_hat: 1.0
    beta_hat: -0.0001
    delta_hat: -0.1
    
lateral_controller_node:
  ros__parameters:
    frequency: 50.0
    wheelbase: 0.5

    k_a1: 1.0
    k_a2: 2.0