/**/model_simulation:
  ros__parameters:
    alpha: 0.012                # Unknown input gain
    beta: -0.0001               # Unknown damping coefficient
    delta: -0.1                 # Fixed unknown disturbance
    wheelbase: 0.5              # Wheelbase (L)
    base_frame: "robot_bs"       # Name for this robot instance
    R: 20.0

/**/longitudinal_controller:
  ros__parameters:
    gamma_alpha: 0.001
    gamma_beta: 0.0001
    gamma_delta: 0.01
    alpha_bar_hat: 1.0
    beta_hat: -0.0001
    delta_hat: -0.1

/**/lateral_controller:
  ros__parameters:
    wheelbase: 0.5
    R: 20.0

/**/formation_controller:
  ros__parameters:
    namespace: "robot"
    k_s: 0.6
    k_l: 0.1
    k_n: 0.06           # Smooth deadzone design constant
    n_bar: 0.4          # Bounded noise threshold (m)

/**/road_adaptation:
  ros__parameters:
    R: 20.0