model_simulation_node:
  ros__parameters:
    alpha: 0.012                # the unknown input gain
    beta: -0.01               # the unknown damping coefficient
    delta: -0.1                 # a fixed unknown disturbance
    wheelbase: 2.5              # wheelbase (L)
    base_frame: "robot_bs"       # name for this robot instance

    R: 20.0
    frequency: 100.0             # integration rate [Hz]
    s0: 0.0                     # initial s (longitudinal position)
    l0: 0.0                     # initial l (lateral position)
    psi0: 0.0                   # initial psi (yaw/heading angle)
    v0: 0.0                     # initial velocity

    # Dynamic parameters
    # torque: 100.0               # the input torque
    # phi: 0.05                   # the input steering angle

longitudinal_controller_node:
  ros__parameters:
    gamma_alpha: 0.001
    gamma_beta: 0.0001
    gamma_delta: 0.01

    k_1: 5.0
    k_2: 0.5

    # v_des: 25.0
    frequency: 20.0

    alpha_bar_hat: 1.0
    beta_hat: -0.0001
    delta_hat: -0.1
    
lateral_controller_node:
  ros__parameters:
    frequency: 20.0
    wheelbase: 2.5
    R: 20.0

    k_a1: 1.5
    k_a2: 3.0

formation_controller_node:
  ros__parameters:
    # id: 1.0
    neighbor_id: [2]    # IDs of topological neighbors
    frequency: 20.0
    namespace: "robot"
    
    k_s: 0.6
    k_l: 0.1
    k_n: 0.06           # Smooth deadzone design constant

    v_f: 15.0           # Desired cruise speed (m/s)
    n_bar: 0.4          # Bounded noise threshold (m)

road_adaptation_node:
  ros__parameters:
    R: 20.0
    frequency: 20.0